var NAV_BAR =   '<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">'
            +    '<!-- Left navbar links -->'
            +        '<ul class="navbar-nav">'
            +            '<li class="nav-item">'
            +                '<a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>'
            +            '</li>'
            +   '<!-- Right nav link --> '
            +        '</ul>'
            +       '<ul class="navbar-nav ml-auto">'
            +            '<li class="nav-item dropdown">'
            +                '<a class="nav-link" data-toggle="dropdown" href="#"><i class="fas fa-user-circle"></i></a>'
            +                    '<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">'
            +                        '<span class="dropdown-header">Mami Piyur Paw Parail</span>'
            
            +                        '<div class="dropdown-divider"></div>'
            +                        '<div class="dropdown-item center">'
            +                           '<img class="circle-img-100 border-naranja" src="../../assets/img/mami-piyur.jpg"/>'
            +                        '</div>'
            +                        '<div class="dropdown-divider"></div>'
            +                            '<div class="dropdown-divider"></div>'
            +                                '<a href="./change-password.html" class="dropdown-item">'
            +                                    '<i class="fas fa-key mr-2"></i> Change Password'
            +                                '</a>'
            +                            '<div class="dropdown-divider"></div>'
            +                                '<a href="../../index.html" class="dropdown-item">'
            +                                    '<i class="fas fa-sign-out-alt mr-2"></i> Sign Out'
            +                                '</a>'
            +                       '</div>'
            +            '</li>'
            +        '</ul>'
            +    '</nav>'
            +    '<!-- END OF TOP NAVBAR -->'
            +    '<!-- SIDE NAVBAR -->'
            +    '<!-- Main Sidebar Container -->'
            +    '<aside class="main-sidebar sidebar-dark-primary elevation-4" style="height: 100%">'
            +    '<!-- Brand Logo -->'
            +        '<a href="dashboard.html" class="brand-link center">'
            +        '<!-- <img src="../../assets/img/Logo_Negativo_.png" alt="AdminLTE Logo" style="height: 50px !important;">    -->'
            +            '<span class="brand-text font-weight-light noe-display text-white" style="border-left: 3px solid #fbbb21; opacity: 1.0 !important; font-size: 20pt;">&nbsp;Entrenador</span>'
            +        '</a>'
            +        '<!-- Sidebar -->'
            +        '<div class="sidebar">'
            +        '<!-- Sidebar user panel (optional) -->'
            +            '<div class="user-panel mt-3 pb-3 mb-3 d-flex">'
            +                '<div class="image">'
            +                    '<img src="../../assets/img/mami-piyur.jpg" class="img-circle elevation-2" alt="User Image">'
            +                '</div>'
            +                '<div class="info">'
            +                    '<a href="./user-profile.html" class="d-block">Mami Piyur Paw Parail</a>'
            +                '</div>'
            +            '</div>'
            +            '<!-- Sidebar Menu -->'
            +            '<nav class="mt-2">'
            +                '<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">'
            +                '<!-- Add icons to the links using the .nav-icon class'
            +                'with font-awesome or any other icon font library -->'
            +                    '<li class="nav-item">'
            +                        '<a href="dashboard.html" class="nav-link" id="dashboard">'
            +                            '<i class="nav-icon fas fa-tachometer-alt"></i>'
            +                            '<p>Dashboard</p>'
            +                        '</a>'
            +                    '</li>'
            +                    '<li class="nav-header">TRANSACTIONS</li>'
            +                    '<li id="transactions-treeview" class="nav-item has-treeview">'
            +                        '<a href="#" id="transactions-main-nav-link" class="nav-link">'
            +                            '<i class="nav-icon far fa-clipboard"></i>'
            +                            '<p>Monitor Trainings<i class="fas fa-angle-left right"></i></p>'
            +                        '</a>'
            +                    '<ul class="nav nav-treeview">'
            +                        '<li class="nav-item">'
            +                            '<a href="../../views/admin/my-training-records.html" id="transactions-my-training-records" class="nav-link">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>My Training Records</p>'
            +                            '</a>'
            +                        '</li>'
            +                        '<li class="nav-item">'
            +                            '<a id="transactions-validation-requests" href="../../views/admin/validation-requests.html" class="nav-link">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Validation Requests</p>'
            +                            '</a>'
            +                        '</li>'
            +                        '<li class="nav-item">'
            +                            ' <a id="transactions-deletion-requests" href="../../views/admin/deletion-requests.html" class="nav-link">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                            '<p>Deletion Requests</p>'
            +                            '</a>'
            +                        '</li>'
            +                        '</ul>'
            +                    '</li>'
            +                    '<li class="nav-header">MAINTENANCE</li>'
            +                    '<li class="nav-item has-treeview" id="trainings-treeview">'
            +                        '<a href="#" class="nav-link" id="trainings-main-nav-link">'
            +                            '<i class="nav-icon fas fa-chalkboard-teacher"></i>'
            +                            '<p>'
            +                                'Trainings'
            +                                '<i class="fas fa-angle-left right"></i>'
            +                            '</p>'
            +                        '</a>'
            +                        '<ul class="nav nav-treeview">'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/types.html" class="nav-link" id="trainings-types">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Types</p>'
            +                                '</a>'
            +                            '</li>'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/categories.html" class="nav-link" id="trainings-categories">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Categories</p>'
            +                                '</a>'
            +                            '</li>'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/courses.html" class="nav-link" id="trainings-courses">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Courses</p>'
            +                                '</a>'
            +                            '</li>'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/training-records.html" class="nav-link" id="trainings-training-records">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Training Records</p>'
            +                                '</a>'
            +                            '</li>'
            +                        '</ul>'
            +                    '</li>'

            +                    '<li class="nav-item">'
            +                        '<a href="employees.html" class="nav-link" id="users">'
            +                            '<i class="nav-icon fas fa-user"></i>'
            +                            '<p>Users</p>'
            +                        '</a>'
            +                    '</li>'
            +                    '<li class="nav-header">Reports</li>'
            +                    '<li class="nav-item has-treeview">'
            +                        '<a href="#" class="nav-link">'
            +                            '<i class="nav-icon fas fa-chart-line"></i>'
            +                            '<p>'
            +                                'Generate Reports'
            +                                '<i class="fas fa-angle-left right"></i>'
            +                            '</p>'
            +                        '</a>'
            +                        '<ul class="nav nav-treeview">'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/employee-training.html" class="nav-link">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Employee Training</p>'
            +                                '</a>'
            +                            '</li>'
            +                            '<li class="nav-item">'
            +                                '<a href="../../views/admin/training-courses.html" class="nav-link">'
            +                                '<i class="far fa-circle nav-icon"></i>'
            +                                '<p>Training Course</p>'
            +                                '</a>'
            +                            '</li>'
            +                        '</ul>'
            +                    '</li>'
            +                '</ul>'
            +            '</nav>'
            +        '<!-- /.sidebar-menu -->'
            +        '</div>'
            +    '<!-- /.sidebar -->'
            +    '</aside>';